"""Configuration loading and management for use_rag.

This module provides functions to load, parse, and manage YAML configuration files.
"""

from pathlib import Path
from typing import Any

try:
    import yaml

    YAML_AVAILABLE = True
except ImportError:
    YAML_AVAILABLE = False

from use_rag.utils.generate_prompt import (
    DEFAULT_ENTITY_TYPES,
    DEFAULT_CLAIM_DESCRIPTION,
)

# Default LLM settings
DEFAULT_MODEL = "gemini/gemini-3-flash-preview"
DEFAULT_MAX_GLEANINGS = 1

# Default settings template (YAML format)
DEFAULT_SETTINGS_YAML = """# use_rag Configuration File
# Generated by: use_rag.configs.export_default_settings()

# LLM Client Settings
llm:
  model: "{model}"
  # api_key: "sk-..."  # Optional: uses environment variable if not set

# Graph Extraction Settings
extract_graph:
  entity_types:
{entity_types}
  max_gleanings: {max_gleanings}

# Claims Extraction Settings
extract_claims:
  enabled: true
  entity_specs: "{entity_specs}"
  description: "{claim_description}"
  max_gleanings: {max_gleanings}

# Output Parsing Settings
parsing:
  record_delimiter: "##"
  tuple_delimiter: "<|>"
  completion_marker: "<|COMPLETE|>"
"""


def get_default_config() -> dict[str, Any]:
    """Get default configuration values.

    Returns:
        Dictionary with default configuration.
    """
    return {
        "llm": {
            "model": DEFAULT_MODEL,
        },
        "extract_graph": {
            "entity_types": list(DEFAULT_ENTITY_TYPES),
            "max_gleanings": DEFAULT_MAX_GLEANINGS,
        },
        "extract_claims": {
            "enabled": True,
            "entity_specs": ", ".join(DEFAULT_ENTITY_TYPES),
            "description": DEFAULT_CLAIM_DESCRIPTION,
            "max_gleanings": DEFAULT_MAX_GLEANINGS,
        },
        "parsing": {
            "record_delimiter": "##",
            "tuple_delimiter": "<|>",
            "completion_marker": "<|COMPLETE|>",
        },
    }


def export_default_settings(output_path: str | Path = "settings.yaml") -> Path:
    """Export default settings to a YAML file.

    Args:
        output_path: Path to write the settings file.

    Returns:
        Path to the created file.

    Example:
        >>> from use_rag import export_default_settings
        >>> export_default_settings("my_settings.yaml")
    """
    output_path = Path(output_path)

    entity_types_yaml = "\n".join(f"    - {et}" for et in DEFAULT_ENTITY_TYPES)

    content = DEFAULT_SETTINGS_YAML.format(
        model=DEFAULT_MODEL,
        entity_types=entity_types_yaml,
        max_gleanings=DEFAULT_MAX_GLEANINGS,
        entity_specs=", ".join(DEFAULT_ENTITY_TYPES),
        claim_description=DEFAULT_CLAIM_DESCRIPTION,
    )

    output_path.write_text(content, encoding="utf-8")
    return output_path


def load_config(config_path: str | Path | None = None) -> dict[str, Any]:
    """Load configuration from a YAML file.

    Args:
        config_path: Path to the YAML configuration file.
            If None, returns default configuration.

    Returns:
        Dictionary containing configuration values.

    Raises:
        FileNotFoundError: If the config file doesn't exist.
        ImportError: If PyYAML is not installed.
        yaml.YAMLError: If the config file is invalid YAML.
    """
    if config_path is None:
        return get_default_config()

    if not YAML_AVAILABLE:
        raise ImportError(
            "PyYAML is required for config file loading. "
            "Install with: pip install pyyaml"
        )

    config_path = Path(config_path)
    if not config_path.exists():
        raise FileNotFoundError(f"Config file not found: {config_path}")

    with open(config_path, "r", encoding="utf-8") as f:
        config = yaml.safe_load(f)

    return config or {}


def get_llm_config(config: dict[str, Any]) -> dict[str, Any]:
    """Extract LLM configuration from config dict.

    Args:
        config: The full configuration dictionary.

    Returns:
        Dictionary with LLM settings (model, api_key).
    """
    defaults = get_default_config()["llm"]
    llm_config = config.get("llm", {})
    return {
        "model": llm_config.get("model", defaults["model"]),
        "api_key": llm_config.get("api_key"),
    }


def get_graph_config(config: dict[str, Any]) -> dict[str, Any]:
    """Extract graph extraction configuration from config dict.

    Args:
        config: The full configuration dictionary.

    Returns:
        Dictionary with graph extraction settings.
    """
    defaults = get_default_config()["extract_graph"]
    graph_config = config.get("extract_graph", {})
    return {
        "entity_types": graph_config.get("entity_types", defaults["entity_types"]),
        "max_gleanings": graph_config.get("max_gleanings", defaults["max_gleanings"]),
    }


def get_claims_config(config: dict[str, Any]) -> dict[str, Any]:
    """Extract claims extraction configuration from config dict.

    Args:
        config: The full configuration dictionary.

    Returns:
        Dictionary with claims extraction settings.
    """
    defaults = get_default_config()["extract_claims"]
    claims_config = config.get("extract_claims", {})

    # For entity_specs, also check extract_graph if not specified
    entity_specs = claims_config.get("entity_specs")
    if entity_specs is None:
        graph_config = config.get("extract_graph", {})
        entity_types = graph_config.get("entity_types", DEFAULT_ENTITY_TYPES)
        entity_specs = ", ".join(entity_types)

    return {
        "enabled": claims_config.get("enabled", defaults["enabled"]),
        "entity_specs": entity_specs,
        "description": claims_config.get("description", defaults["description"]),
        "max_gleanings": claims_config.get("max_gleanings", defaults["max_gleanings"]),
    }


def create_extractors_from_config(config_path: str | Path | None = None):
    """Create LLMClient and extractors from configuration.

    This is a convenience function that creates all components from a single config file.

    Args:
        config_path: Path to the YAML configuration file.
            If None, uses default configuration.

    Returns:
        Tuple of (LLMClient, GraphExtractor, ClaimExtractor).

    Raises:
        ImportError: If litellm or openai is not installed.

    Example:
        >>> from use_rag import create_extractors_from_config
        >>> client, graph_ext, claim_ext = create_extractors_from_config("settings.yaml")
        >>> entities, rels = graph_ext.extract("Apple was founded by Steve Jobs.")
    """
    from use_rag import LLMClient, GraphExtractor, ClaimExtractor

    config = load_config(config_path)

    # Create LLM client
    llm_config = get_llm_config(config)
    client = LLMClient(
        model=llm_config["model"],
        api_key=llm_config["api_key"],
    )

    # Create graph extractor
    graph_config = get_graph_config(config)
    graph_extractor = GraphExtractor(
        client=client,
        entity_types=graph_config["entity_types"],
        max_gleanings=graph_config["max_gleanings"],
    )

    # Create claim extractor
    claims_config = get_claims_config(config)
    claim_extractor = ClaimExtractor(
        client=client,
        entity_specs=claims_config["entity_specs"],
        claim_description=claims_config["description"],
        max_gleanings=claims_config["max_gleanings"],
    )

    return client, graph_extractor, claim_extractor
